---
title: "ISS descriptives"
author: "ZH"
date: "2026-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)

library(here)
library(dplyr)
library(tidyr)
library(purrr)
library(ggplot2)
library(Hmisc)
```


```{r ISS_2023}

# load data
iss2023 <- 
  read.csv(here("data", "iss", "H20231491data.csv")) |>
  select(nn,
         Gil,
         MatzavTaasukaM_C,
         PehamimShimushInt, 
         MachshevAvoda, 
         MachshevHipusMeida, 
         MachshevEmail, 
         MachshevWhatsApp, 
         MachshevChat, 
         MachshevBankim, 
         MachshevHoradatKvazim, 
         MachshevKniyot, 
         MachshevGov, 
         MachshevVideo)
         
# check obs
iss2023 |> 
  mutate(internet_for_all_use = as.numeric(PehamimShimushInt == 1 &
                                             MachshevAvoda == 1 &
                                             MachshevHipusMeida == 1 &
                                             MachshevEmail == 1 & 
                                             MachshevWhatsApp == 1 &
                                             MachshevChat == 1 &
                                             MachshevBankim == 1 &
                                             MachshevHoradatKvazim == 1 &
                                             MachshevKniyot == 1 &
                                             MachshevGov == 1 &
                                             MachshevVideo == 1)) |> 
  summarise(
    all.obs = n(),
    all.pop_estimate = sum(nn),
    age.obs = sum(as.numeric(Gil >= 2 & Gil <= 9)),
    age.pop_estimate = sum(as.numeric(Gil >= 2 & Gil <= 9)*nn),
    labor_force.obs = sum(as.numeric(Gil >= 2 & Gil <= 9 & MatzavTaasukaM_C != 3)),
    labor_force.pop_estimate = sum(as.numeric(Gil >= 2 & Gil <= 9 & MatzavTaasukaM_C != 3)*nn),
    internet_daily.obs = sum(as.numeric(Gil >= 2 & Gil <= 9 & MatzavTaasukaM_C != 3 & PehamimShimushInt == 1)),
    internet_daily.pop_estimate = sum(as.numeric(Gil >= 2 & Gil <= 9 & MatzavTaasukaM_C != 3 & PehamimShimushInt == 1)*nn),
    internet_all_use.obs = sum(as.numeric(Gil >= 2 & Gil <= 9 & MatzavTaasukaM_C != 3 & internet_for_all_use == 1)),
    internet_all_use.pop_estimate = sum(as.numeric(Gil >= 2 & Gil <= 9 & MatzavTaasukaM_C != 3 & internet_for_all_use == 1)*nn)
  ) |> 
  pivot_longer(
    cols = everything(),
    names_sep = "\\.",
    names_to = c("criteria", "variable")
  ) |> 
  pivot_wider(names_from = "variable", values_from = "value")
```

``` {r ISS_cross_year}

# load data ----
# data files
iss_data <- 
  list("2019" = "H20191424data.csv",
       "2020" = "H20201453data.csv",
       "2021" = "H20211461data.csv",
       "2022" = "H20221482data.csv",
       "2023" = "H20231491data.csv",
       "2024" = "H20241501data.csv")

# read data
iss_data <- 
  map(iss_data, ~ read.csv(here("data", "iss", .x))) |> 
  map(~ select(.x,
               any_of(c("nn",
                        "Gil",
                        "MatzavTaasukaM_C",
                        "HachnasaAvoda",
                        "AvodaHaimIzun_wp",
                        "MerutzeAvoda_wp",
                        "PehamimShimushInt",
                        "MachshevAvoda",
                        "MachshevHipusMeida",
                        "MachshevEmail",
                        "MachshevChat",
                        "MachshevChat_C",
                        "MachshevHoradatKvazim",
                        "MachshevKniyot",
                        "MachshevGov",
                        "MachshevVideo")))) 
# rename
col_to_change <- colnames(iss_data[["2020"]]) == "MachshevChat_C"
colnames(iss_data[["2020"]])[col_to_change] <- "MachshevChat"
rm(col_to_change)

# consolidate to one table 
iss_data <- bind_rows(iss_data,.id = "year")

# filter to by age, LF participation, daily use
iss_data <- 
  iss_data |> 
  filter(Gil >= 2 & Gil <= 9, MatzavTaasukaM_C != 3, PehamimShimushInt == 1) |> 
  mutate(internet_for_all_use = as.numeric(MachshevAvoda == 1 &
                                             MachshevHipusMeida == 1 &
                                             MachshevEmail == 1 & 
                                             MachshevChat == 1 &
                                             MachshevHoradatKvazim == 1 &
                                             MachshevKniyot == 1 &
                                             MachshevGov == 1 &
                                             MachshevVideo == 1) |> factor(levels = 0:1,
                                                                           labels = c("non intensive user",
                                                                                      "intensive user")),
         year = as.numeric(year))

# fix NAs
iss_data <- 
  iss_data |> 
  mutate(
    HachnasaAvoda = if_else(HachnasaAvoda <= 11, HachnasaAvoda, NA),
    HachnasaAvoda = if_else(HachnasaAvoda == 11, 0, HachnasaAvoda),
    AvodaHaimIzun_wp = if_else(AvodaHaimIzun_wp <= 4, AvodaHaimIzun_wp, NA),
    MerutzeAvoda_wp = if_else(MerutzeAvoda_wp <= 4, MerutzeAvoda_wp, NA)
    
  )

# fix factors
fix_factor_HachnasaAvoda <- function(x) {
  factor(x,
         levels = 0:10,
         labels = c("No income",
                    "2000 or less",
                    "2,001-3,000",
                    "3,001-4,000",
                    "4,001-5,000",
                    "5,001-6,000",
                    "6,001-7,500",
                    "7,501-10,000",
                    "10,001-14,000",
                    "14,001-21,000",
                    "over 21,000"))
}

fix_factor_satisfied <- function(x) {
  factor(x,
         levels = 1:4,
         labels = c("Very satisfied",
                    "Satisfied",
                    "Unsatisfied",
                    "Very unsatisfied"))
}

# analysis per year ----
plot_data <- 
  iss_data |> 
  group_by(year, internet_for_all_use) |> 
  summarise(across(c("HachnasaAvoda", "AvodaHaimIzun_wp", "MerutzeAvoda_wp"),
                   list(first_quartile = ~ wtd.quantile(.x, probs = 0.25, weights = nn, na.rm = T),
                        median = ~ wtd.quantile(.x, probs = 0.5, weights = nn, na.rm = T),
                        third_quartile = ~ wtd.quantile(.x, probs = 0.75, weights = nn, na.rm = T)),
                   .names = "{col}.{fn}")) |> 
  ungroup() |> 
  pivot_longer(cols = -c("year", "internet_for_all_use"),
               names_sep = "\\.",
               names_to = c("variable", "metric")) |> 
  pivot_wider(names_from = "variable", values_from = "value") |> 
  mutate(HachnasaAvoda = fix_factor_HachnasaAvoda(HachnasaAvoda),
         AvodaHaimIzun_wp = fix_factor_satisfied(AvodaHaimIzun_wp) |> forcats::fct_rev(),
         MerutzeAvoda_wp = fix_factor_satisfied(MerutzeAvoda_wp) |> forcats::fct_rev(),
         group_var = paste(metric, internet_for_all_use))
 
plot_data |>  
  ggplot(aes(year, HachnasaAvoda, colour = internet_for_all_use, linetype = metric, group = group_var)) +
  geom_vline(xintercept = 2023, linetype = "dashed", color = "grey30") +
  geom_line(lwd = 1) +
  scale_linetype_manual(values = c("dashed", "solid", "dashed")) +
  labs(color = "Daily internet use type",
       y = "Net labor income",
       x = "Year",
       linetype = "Metric",
       title = "Figure 1: No structural break in labor income among internet user types") +
  theme_bw()

ggsave(here("outputs", "income by use type.png"), dpi = 500)

plot_data |>  
  ggplot(aes(year, MerutzeAvoda_wp, colour = internet_for_all_use, linetype = metric, group = group_var)) +
  geom_vline(xintercept = 2023, linetype = "dashed", color = "grey30") +
  geom_line(data = plot_data |>  filter(internet_for_all_use == "non intensive user"),
            lwd = 1, 
            position = position_nudge(y = 0.01)) +
  geom_line(data = plot_data |>  filter(internet_for_all_use == "intensive user"),
            lwd = 1, 
            position = position_nudge(y = -0.01)) +
  scale_linetype_manual(values = c("dashed", "solid", "dashed")) +
  labs(color = "Daily internet use type",
       y = "General work satisfaction",
       x = "Year",
       linetype = "Metric") +
  # facet_wrap(~internet_for_all_use)+
  theme_bw()

plot_data |>  
  ggplot(aes(year, AvodaHaimIzun_wp, colour = internet_for_all_use, linetype = metric, group = group_var)) +
  geom_vline(xintercept = 2023, linetype = "dashed", color = "grey30") +
  geom_line(data = plot_data |>  filter(internet_for_all_use == "non intensive user"),
            lwd = 1, 
            position = position_nudge(y = 0.01)) +
  geom_line(data = plot_data |>  filter(internet_for_all_use == "intensive user"),
            lwd = 1, 
            position = position_nudge(y = -0.01)) +
  scale_linetype_manual(values = c("dashed", "solid", "dashed")) +
  labs(color = "Daily internet use type",
       y = "Life-work balance satisfaction",
       x = "Year",
       linetype = "Metric") +
  # facet_wrap(~internet_for_all_use)+
  theme_bw()
```